set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN P20 } [get_ports fpga_rst]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN Y18 } [get_ports fpga_clk]

set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  Y9 } [get_ports Switch[23]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  W9 } [get_ports Switch[22]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  Y7 } [get_ports Switch[21]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  Y8 } [get_ports Switch[20]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN AB8 } [get_ports Switch[19]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN AA8 } [get_ports Switch[18]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  V8 } [get_ports Switch[17]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  V9 } [get_ports Switch[16]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN AB6 } [get_ports Switch[15]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN AB7 } [get_ports Switch[14]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  V7 } [get_ports Switch[13]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN AA6 } [get_ports Switch[12]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  Y6 } [get_ports Switch[11]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  T6 } [get_ports Switch[10]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  R6 } [get_ports Switch[ 9]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  V5 } [get_ports Switch[ 8]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  U6 } [get_ports Switch[ 7]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  W5 } [get_ports Switch[ 6]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  W6 } [get_ports Switch[ 5]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  U5 } [get_ports Switch[ 4]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  T5 } [get_ports Switch[ 3]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  T4 } [get_ports Switch[ 2]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  R4 } [get_ports Switch[ 1]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  W4 } [get_ports Switch[ 0]]

set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  P2 } [get_ports button[4]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  P4 } [get_ports button[3]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  P5 } [get_ports button[2]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  P1 } [get_ports button[1]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  R1 } [get_ports button[0]]

set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN A18 } [get_ports dig_en[7]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN A20 } [get_ports dig_en[6]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN B20 } [get_ports dig_en[5]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN E18 } [get_ports dig_en[4]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN F18 } [get_ports dig_en[3]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN D19 } [get_ports dig_en[2]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN E19 } [get_ports dig_en[1]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN C19 } [get_ports dig_en[0]]

set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN F15 } [get_ports DN_A ]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN F13 } [get_ports DN_B ]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN F14 } [get_ports DN_C ]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN F16 } [get_ports DN_D ]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN E17 } [get_ports DN_E ]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN C14 } [get_ports DN_F ]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN C15 } [get_ports DN_G ]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN E13 } [get_ports DN_DP]

set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN K17 } [get_ports led[23]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN L13 } [get_ports led[22]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN M13 } [get_ports led[21]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN K14 } [get_ports led[20]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN K13 } [get_ports led[19]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN M20 } [get_ports led[18]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN N20 } [get_ports led[17]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN N19 } [get_ports led[16]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN M17 } [get_ports led[15]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN M16 } [get_ports led[14]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN M15 } [get_ports led[13]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN K16 } [get_ports led[12]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN L16 } [get_ports led[11]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN L15 } [get_ports led[10]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN L14 } [get_ports led[ 9]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN J17 } [get_ports led[ 8]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN F21 } [get_ports led[ 7]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN G22 } [get_ports led[ 6]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN G21 } [get_ports led[ 5]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN D21 } [get_ports led[ 4]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN E21 } [get_ports led[ 3]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN D22 } [get_ports led[ 2]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN E22 } [get_ports led[ 1]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN A21 } [get_ports led[ 0]]
